spring:
  application:
    name: authentication-server
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: wishlist
    password: example
  liquibase:
    change-log: classpath:liquibase/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5432/postgres
    user: wishlist
    password: example
    enabled: true

application:
  security:
    jwt:
      securityWord: 'securityWord'
      tokenExpired: 360000

logging:
  level:
    root: info